#!/command/with-contenv bash

SSH_USER_HOME="${SSH_USER_HOME:-"/home/$SSH_USER"}"

# Create our SSH user
groupadd -r -g $PGID $SSH_GROUP
useradd --no-log-init -m -r -s /usr/bin/bash -d $SSH_USER_HOME -u $PUID -g $PGID $SSH_USER

if [[ $S6_LOGGING != 1 ]]; then
echo '
--------------------------------------------------------------------
 ____                             ____  _     _        _   _
/ ___|  ___ _ ____   _____ _ __  / ___|(_) __| | ___  | | | |_ __
\___ \ / _ \  __\ \ / / _ \  __| \___ \| |/ _` |/ _ \ | | | |  _ \
 ___) |  __/ |   \ V /  __/ |     ___) | | (_| |  __/ | |_| | |_) |
|____/ \___|_|    \_/ \___|_|    |____/|_|\__,_|\___|  \___/| .__/
                                                            |_|

Brought to you by serversideup.net
--------------------------------------------------------------------'

echo '
To support Server Side Up projects visit:
https://serversideup.net/sponsor
-------------------------------------
👋 SSH User Information
-------------------------------------'
echo "
User uid:    $(id -u $SSH_USER)
User gid:    $(id -g $SSH_USER)
Username:    $SSH_USER
User Group:  $SSH_GROUP
-------------------------------------
"
fi