name: Docker Publish (Edge Images)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/**
      - generate-tags.sh
jobs:
  build-edge-images:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    secrets: inherit
    with:
      release_type: 'edge'

  update_container_readme:
    runs-on: ubuntu-24.04
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_README_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_README_PASSWORD }}
        with:
          destination_container_repo: serversideup/docker-ssh
          provider: dockerhub
          short_description: 'Simple SSH container. Great for secure connections into clusters.'
          readme_file: 'README.md'