name: Docker Publish (Beta Images)

on:
  workflow_dispatch:
  release:
    types: [prereleased]
jobs:
  build-beta-images:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    secrets: inherit
    with:
      release_type: 'beta'
